LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MULTILIB      := both
LOCAL_MODULE        := libomxprox.${TARGET_BOOTLOADER_BOARD_NAME}
LOCAL_SRC_FILES_32  := lib/libomxprox.${TARGET_BOOTLOADER_BOARD_NAME}.so
LOCAL_SRC_FILES_64  := lib64/libomxprox.${TARGET_BOOTLOADER_BOARD_NAME}.so
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_EXPORT_C_INCLUDE_DIRS := $(LOCAL_PATH)/include/OpenMAX/libomxil-prox/include
ifeq ($(BOARD_VNDK_VERSION),current)
LOCAL_VENDOR_MODULE := true
endif
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MULTILIB      := both
LOCAL_MODULE        := libsc.${TARGET_BOOTLOADER_BOARD_NAME}
LOCAL_SRC_FILES_32  := lib/libsc.${TARGET_BOOTLOADER_BOARD_NAME}.so
LOCAL_SRC_FILES_64  := lib64/libsc.${TARGET_BOOTLOADER_BOARD_NAME}.so
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_SUFFIX := .so
ifeq ($(BOARD_VNDK_VERSION),current)
LOCAL_VENDOR_MODULE := true
endif
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MULTILIB      := both
LOCAL_MODULE        := libvideo-out.${TARGET_BOOTLOADER_BOARD_NAME}
LOCAL_SRC_FILES_32  := lib/libvideo-out.${TARGET_BOOTLOADER_BOARD_NAME}.so
LOCAL_SRC_FILES_64  := lib64/libvideo-out.${TARGET_BOOTLOADER_BOARD_NAME}.so
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_SUFFIX := .so
ifeq ($(BOARD_VNDK_VERSION),current)
LOCAL_VENDOR_MODULE := true
endif
include $(BUILD_PREBUILT)

